/**
 * Utilized LLM to fill ~80-85% of course data below, employing the following strategy:
 * Displayed to it a sample of course data I would provide from this site: https://engineering.calendar.utoronto.ca/search-courses
 * Sample data looks as follows:
 * ECE430H1 - Analog Integrated Circuits
 * Credit Value: 0.50
 * Hours: 38.4L/12.8T/19.2P
 * Review of MOSFET semiconductor device equations. Noise in electronic devices. Review of single-stage amplifiers and frequency response, including noise analysis. Basic CMOS op amp. Op amp compensation. Advanced op amp circuits: telescopic and folded-cascode op amps. Fully-differential op amps. Common mode feedback.
 * Prerequisite: ECE331H1 or ECE354H1
 * Exclusion: ECE530H1
 * 
 * I then gave it my desired outcome:
 * {
    description:
      "Review of MOSFET semiconductor device equations. Noise in electronic devices. Review of single-stage amplifiers and frequency response, including noise analysis. Basic CMOS op amp. Op amp compensation. Advanced op amp circuits: telescopic and folded-cascode op amps. Fully-differential op amps. Common mode feedback.",
    code: "ECE430H1",
    title: "Analog Integrated Circuits",
    area: [],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE331H1", "ECE354H1"],
    corequisites: [],
    exclusions: ["ECE530H1"],
    recommendedPrep: [],
  },
  * I then copied & pasted these descriptions for ~80-85% of the courses below into the LLM, pasted its response below, 
  * and manually added the area, prerequisiteAmount, and corequisiteAmount fields
 */

export const COURSE_DATA = [
  {
    description:
      "Geometric Optics: Spherical surfaces, lenses and mirrors, optical imaging systems, matrix method, and aberrations. Polarization: Polarizer and polarizations, anisotropic materials, dichroism, birefringence, index ellipsoid, waveplates, optical activity, Faraday effect. Interference: superposition of waves, longitudinal and transverse coherence, Young's double-slit experiment, Michelson and Fabry-Perot interferometer, thin-films. Diffraction and Fourier Optics: diffraction theory, single and double slits, diffraction gratings, spatial filtering, basic optical signal processing.",
    code: "ECE318H1",
    title: "Fundamentals of Optics",
    area: ["PHOTONICS_SEMICONDUCTOR"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE221H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: ["ECE320H1", "ECE357H1"],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Electrical behaviour of semiconductor structures and devices. Metal-semiconductor contacts; pn junctions, diodes, photodetectors, LED's; bipolar junction transistors, Ebers-Moll and hybrid-pi models; field effect transistors, MOSFET, JFET/MESFET structures and models; thyristors and semiconductor lasers.",
    code: "ECE335H1",
    title: "Introduction to Electronic Devices",
    area: ["PHOTONICS_SEMICONDUCTOR"],
    lectureHours: 36.6,
    tutorialHours: 24.4,
    practicalHours: 18.3,
    prerequisites: ["MAT291H1", "ECE221H1", "ECE231H1"],
    corequisites: [],
    exclusions: ["MSE335H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "The human visual interface is rapidly evolving with the emergence of smart glasses, AR/VR wearable display, and autonomous vehicles. This course examines the photonic devices and integrated systems that underline such technologies, and how they are shaped by human visual perception and acuity. Advanced integrated photonic systems in optical display and sensing will be deconstructed and the underlying fundamental concepts studied. Topics include introduction to: heads up and wearable display, optical lidar, optical fiber, waveguide circuits, holography, optical switches, light sources (LED, laser), detectors and in imaging sensors",
    code: "ECE427H1",
    title: "Photonic Devices",
    area: ["PHOTONICS_SEMICONDUCTOR"],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 0,
    prerequisites: ["ECE318H1", "ECE320H1", "ECE357H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "An introduction to the fundamentals of micro- and nano-fabrication processes with emphasis on cleanroom practices. The physical principles of optical lithography, electron-beam lithography, alternative nanolithography techniques, and thin film deposition and metrology methods. The physical and chemical processes of wet and dry etching. Cleanroom concepts and safety protocols. Sequential micro-fabrication processes involved in the manufacture of microelectronic and photonic devices. Imaging and characterization of micro- and nano-structures. Examples of practical existing and emerging micro- and nano-devices. Limited enrollment.",
    code: "ECE442H1",
    title: "Introduction to Micro- and Nano-Fabrication Technologies",
    area: ["PHOTONICS_SEMICONDUCTOR"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 25.6,
    prerequisites: ["ECE335H1", "ECE350H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "This course introduces the principles of quantum physics and uses them to understand the behaviour of semiconductors. Topics to be covered include wave-particle duality, Schrodinger's equation, energy quantization, quantum mechanical tunnelling, electrons in crystalline semiconductors, and other physical concepts that form the basis for nanotechnology, microelectronics and optoelectronics.",
    code: "ECE330H1",
    title: "Quantum and Semiconductor Physics",
    area: ["PHOTONICS_SEMICONDUCTOR"],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 0,
    prerequisites: ["ECE221H1", "ECE231H1"],
    corequisites: [],
    exclusions: ["MSE235H1"],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "The introduction to VLSI fabrication techniques, integrated circuit designs and advanced semiconductor devices will give a proper perspective of the past, present and future trends in the VLSI industry. Following the evolution of MOS and bipolar devices, digital and analog CMOS, BiCMOS, deep submicron CMOS, SOI-CMOS, RF-CMOS and HV-CMOS technologies will be studied. Special attention will be given to the physical scaling limits such as short channel effects. In addition, CAD tools and design methodology for the development of advanced semiconductor devices and integrated circuits will be introduced in the laboratory environment. These include the simulation of device fabrication, device characteristics, device modeling, circuit layout and design verification. Finally, advanced technology such as GaN HEMTs, graphene devices, carbon nano-tube devices, power devices, heterojunctions, InP and GaSb HBTs will also be studied.",
    code: "ECE437H1",
    title: "VLSI Technology",
    area: ["PHOTONICS_SEMICONDUCTOR", "ANALOG_DIGITAL"],
    lectureHours: 38.4,
    tutorialHours: 0,
    practicalHours: 38.4,
    prerequisites: ["ECE331H1", "ECE334H1", "ECE354H1", "ECE335H1", "ECE350H1"],
    corequisites: [],
    exclusions: ["ECE535H1", "ECE534H1"],
    recommendedPrep: [],
    prerequisiteAmount: 2,
    corequisiteAmount: 0,
  },
  {
    description:
      "This course provides an introduction to optical communication systems and networks at the system and functional level. Applications range from telecommunication networks (short to long haul) to computing networks (chip-to-chip, on chip communications, optical backplanes). Basic principles of optical transmission and associated components used for transmission of light and optical networks; system design tools for optical links; multi-service system requirements; optical network design tools (routing and wavelength assignment), network management and survivability.",
    code: "ECE469H1",
    title: "Optical Communications and Networks",
    area: [
      "PHOTONICS_SEMICONDUCTOR",
      "CONTROL_COMM_SIGNAL",
      "HARDWARE_NETWORKS",
    ],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "High-efficiency energy conversion via switched-mode power electronic circuits: design and steady-state modeling of DC/DC converters, DC/AC converters using pulse-width modulation. Transistor switch realization and basic efficiency analysis in power electronic converters. AC power quality and power factor, including non-sinusoidal currents. Energy conversion via magnetic devices: Faraday's law for time varying fields, characterization of hysteresis and eddy current losses in magnetic materials, modelling of magnetic circuits, transformer and inductor modelling and design. Introduction to electromechanical energy conversion: Lorentz Force, concepts of energy, co-energy, forces between ferromagnetic materials carrying flux, simple magnetic actuators, introduction to synchronous machines.",
    code: "ECE314H1",
    title: "Fundamentals of Electrical Energy Systems",
    area: ["ENERGY_ELECTROMAGNETICS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE212H1", "ECE221H1", "ECE231H1"],
    corequisites: ["ECE320H1"],
    exclusions: ["ECE349H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Design and steady-state modeling of DC/DC and DC/AC (single- and three-phase) converters using modified-square-wave and pulse-width modulation. Three-phase, balanced connections and analysis of harmonics via superposition. Modeling of non-ideal components in power electronic converters to determine practical conversion ratios and efficiency. Energy conversion based on magnetic field interactions: Faraday's law for time varying fields, characterization of primary loss mechanisms (hysteresis and eddy currents) in magnetic materials, magnetic circuit analysis, transformer and inductor modeling and design. Introduction to electromechanical energy conversion: Lorentz Force, calculation of electromechanical forces in conservative systems using energy and co-energy, simple magnetic actuators and sensors, introduction to synchronous machines.",
    code: "ECE349H1",
    title: "Introduction to Energy Systems",
    area: ["ENERGY_ELECTROMAGNETICS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: [""],
    corequisites: [""],
    exclusions: ["ECE314H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Voltage and current waves on a general transmission line, characteristic impedance, reflections from the load and source, transients on a transmission line, Smith's chart and impedance matching. Maxwell's equations, wave equation, constitutive relations, dispersion, boundary conditions. Plane wave propagation in lossless and lossy media, polarization, power flow and Poynting vector. Plane wave reflection and transmission at material boundaries. Waveguides; propagating and evanescent waveguide modes and cut-off frequencies.",
    code: "ECE320H1",
    title: "Fields and Waves",
    area: ["ENERGY_ELECTROMAGNETICS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: [],
    corequisites: ["ECE314H1"],
    exclusions: ["ECE357H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description: "An introduction to transmission lines: voltage and current waves, characteristic impedance, reflections from the load and source, transients on a transmission line, Smith's chart, impedance matching. Fundamentals of electromagnetic theory: Maxwell's equations, boundary conditions, wave equation and its solutions in lossless and lossy media. Constitutive relations and dispersion. Plane wave propagation, reflection and transmission at boundaries. Waveguides; propagating and evanescent waveguide modes and cut-off frequencies. Introduction to radiation and antennas.",
    code: "ECE357H1",
    title: "Electromagnetic Fields",
    area: ["ENERGY_ELECTROMAGNETICS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE259H1"],
    corequisites: [],
    exclusions: ["ECE320H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Losses in conductors and dielectrics; RF and microwave transmission lines; transients on transmission lines; matching networks; planar transmission lines (microstrip, stripline, coplanar waveguide); design with scattering parameters; 3- and 4-port RF devices (power dividers/combiners, couplers, isolators & circulators); coupled lines and devices; microwave active circuits (RF amplifiers, mixers, and receiver front ends); RF and microwave filters. The hands-on laboratories engage students in the design, simulation, fabrication, and test of practical passive and active microwave circuits using industry-standard RF/microwave simulation tools and measurement systems.",
    code: "ECE424H1",
    title: "Microwave Circuits (formerly ECE524H1)",
    area: ["ENERGY_ELECTROMAGNETICS", "ANALOG_DIGITAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: [],
    corequisites: [],
    exclusions: ["ECE524H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "The course focuses on power electronic converters utilized in applications ranging from low-power mobile devices to higher power applications such as electric vehicles, server farms, microgrids, and renewable energy systems. Concepts covered include the principles of efficient electrical energy processing (dc-dc, dc/ac, and ac/ac) through switch-mode energy conversion, converter loss analysis, large- and small-signal modeling of power electronic circuits and controller design.",
    code: "ECE520H1",
    title: "Power Electronics",
    area: ["ENERGY_ELECTROMAGNETICS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 16.2,
    prerequisites: ["ECE314H1", "ECE349H1", "ECE359H1"],
    corequisites: [],
    exclusions: ["ECE514H1", "ECE533H1"],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Presents the concepts of short-circuit fault analysis, protective relaying, and automation in power systems. The course starts by discussing the causes and types of short-circuit faults using real-world examples. The consequences of faults for different power system components are reviewed using event reports from field data. The method of symmetrical components for analyzing unbalanced three-phase systems are introduced. Analytical methods and computer-based approaches for deriving fault voltages and currents are discussed and the effect of system grounding during transient conditions, including faults, are introduced. Students also learn the concept of power system automation and its role in monitoring, protection, and control of modern power systems. Critical devices used in an automation system, such as breakers, relays, reclosers, capacitor bank controllers, and tap changer controllers are presented.",
    code: "ECE526H1",
    title: "Power System Protection and Automation",
    area: ["ENERGY_ELECTROMAGNETICS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 16.2,
    prerequisites: ["ECE313H1", "ECE314H1", "ECE349H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Three-phase systems; steady-state transmission line model; symmetrical three-phase faults; power system stability; symmetrical components; unsymmetrical faults and fault current calculation; distribution network; equivalent steady-state model of voltage-sourced converter; distributed energy resources (DR); distributed energy storage; interface between DR and power system.",
    code: "ECE313H1",
    title: "Energy Systems and Distributed Generation (formerly ECE413H1)",
    area: ["ENERGY_ELECTROMAGNETICS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: [],
    corequisites: [],
    exclusions: ["ECE413H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Analysis and design of systems employing radio waves, covering both the underlying electromagnetics and the overall system performance aspects such as signal-to-noise ratios. Transmission/reception phenomena include: electromagnetic wave radiation and polarization; elementary and linear dipoles; directivity, gain, efficiency; integrated, phased-array and aperture antennas; beam-steering; Friis transmission formula and link budget. Propagation phenomena include: diffraction and wave propagation over obstacles; multipath propagation; atmospheric and ionospheric effects. Receiver design aspects include: radio receiver architectures, receiver figures of merit, noise in cascaded systems, noise figure, and noise temperature. System examples are: terrestrial communication systems; satellite communications; radar; radiometric receivers; software-defined radio.",
    code: "ECE422H1",
    title: "Radio and Microwave Wireless Systems",
    area: ["ENERGY_ELECTROMAGNETICS", "CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE320H1", "ECE357H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Electric drives comprise electric machines (i.e. motors/generators) together with power electronic actuation to enable the control of mechanical motion. Topics include electro-mechanical mechanisms for torque production relevant to rotating machines, speed-torque diagrams, DC machine analysis, dynamics and torque/speed/position control, introduction to space vectors and their application to motion control of synchronous machines and stepper motors. Steady state and variable speed operation of the induction machine using constant flux control is also be covered.",
    code: "ECE463H1",
    title: "Electric Drives",
    area: ["ENERGY_ELECTROMAGNETICS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE314H1", "ECE315H1", "ECE349H1", "ECE359H1"],
    corequisites: ["ECE311H1", "ECE356H1", "AER372H1"],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 1,
  },
  {
    description:
      "Transistor amplifiers with an emphasis on integrated circuit (IC) design. Building blocks include differential and multistage amplifiers, IC biasing techniques, and output stage design. Frequency response of amplifiers at low, medium and high frequencies. Feedback amplifier analysis. Stability and compensation techniques for amplifiers using negative feedback.",
    code: "ECE331H1",
    title: "Analog Electronics",
    area: ["ANALOG_DIGITAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE212H1", "ECE231H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Digital design techniques for integrated circuits. The emphasis will be on the design of logic gates at the transistor level. A number of different logic families will be described, but CMOS will be emphasized. Review of: device modeling, IC processing, and Spice simulation, simplified layout rules, inverter noise margins, transient response, and power dissipation, traditional CMOS logic design, transmission gates, RC timing approximations, input-output circuits, latches and flipflops, counters and adders, decoders and muxes, dynamic gates, SRAMs, DRAMs, and EEPROMs.",
    code: "ECE334H1",
    title: "Digital Electronics",
    area: ["ANALOG_DIGITAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE241H1", "ECE231H1", "ECE253H1", "ECE360H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 3,
    corequisiteAmount: 0,
  },
  {
    description:
      "Review of MOSFET semiconductor device equations. Noise in electronic devices. Review of single-stage amplifiers and frequency response, including noise analysis. Basic CMOS op amp. Op amp compensation. Advanced op amp circuits: telescopic and folded-cascode op amps. Fully-differential op amps. Common mode feedback.",
    code: "ECE430H1",
    title: "Analog Integrated Circuits",
    area: ["ANALOG_DIGITAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE331H1", "ECE354H1"],
    corequisites: [],
    exclusions: ["ECE530H1"],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "A review of the principles and practical implementation of quantum processors based on solid state superconducting and semiconductor spin qubits. The focus is on hardware with no overlap with existing Quantum Information or proposed Quantum Algorithms undergraduate EngSci or CompSci courses. A top-down approach is taken starting from the quantum processor architecture and building block specification, to qubit and control and readout circuit modelling, design, fabrication and testing. Topics include the basics of quantum mechanics and quantum computing, superconducting and semiconductor spin qubit physics, fabrication and characterization techniques for qubits, and classical control and readout of qubits. Students will gain hands-on experience with the engineering of a quantum computer, deriving specifications for its quantum and classical hardware building blocks, and designing, modelling, simulating, and testing qubits, control and readout circuits for quantum processors.",
    code: "ECE435H1",
    title: "Quantum Computing Hardware",
    area: ["PHOTONICS_SEMICONDUCTOR", "ANALOG_DIGITAL"],
    lectureHours: 36.6,
    tutorialHours: 24.4,
    practicalHours: 18.3,
    prerequisites: [
      "ECE216H1",
      "ECE355H1",
      "ECE286H1",
      "MIE286H1",
      "ECE302H1",
      "ECE335H1",
      "ECE350H1",
      "ECE231H1",
      "ECE360H1",
      "ECE320H1",
      "ECE357H1",
    ],
    corequisites: [],
    exclusions: [],
    recommendedPrep: ["PHY365H1"],
    prerequisiteAmount: 5,
    corequisiteAmount: 0,
  },
  {
    description:
      "Waves, physical, and musical acoustics, musical instruments, electrical and mechanical interfaces for musical expression, electroacoustic transducers, sensing and metasensing, ultrasound, measurement (phase-coherent detection), and physiological acoustics. Speech, music, and interface processing and signal processing, including aspects of the auditory system. Wearable technologies for audio. Engineering aspects of acoustic and electroacoustic design. Electrical models of acoustic systems. Noise, noise-induced hearing loss, and noise control. Introduction to vision and other modalities. Creative and artistic systems and interfaces.",
    code: "ECE446H1",
    title: "Audio, Acoustics and Sensing",
    area: ["ANALOG_DIGITAL", "CONTROL_COMM_SIGNAL"],
    lectureHours: 36.6,
    tutorialHours: 0,
    practicalHours: 18.3,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "This course will provide students with an overview of continuous-time and discrete-time signal processing techniques, and the analysis and design of analog and mixed-signal circuit building blocks used in modern electronic systems. Topics covered include: analysis, specification, simulation, and design of continuous-time filters with linear transconductors and op-amps; phase-domain model, noise model, and design methodology for low phase noise Phase Lock Loops and associated building blocks (VCO, phase-frequency detector, charge pump); discrete-time signal analysis using z-transform; discrete-time filter design based on switched capacitors; as well as fundamentals, architectures, building blocks, and characterization techniques for digital-to-analog and analog-to-digital converters.",
    code: "ECE412H1",
    title: "Analog Signal Processing Circuits",
    area: ["ANALOG_DIGITAL"],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 0,
    prerequisites: ["ECE331H1", "ECE354H1"],
    corequisites: [],
    exclusions: ["ECE512H1"],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Advanced digital systems design concepts including project planning, design flows, embedded processors, hardware/software interfacing and interactions, software drivers, embedded operating systems, memory interfaces, system-level timing analysis, clocking and clock domains. A significant design project is undertaken and implemented on an FPGA development board.",
    code: "ECE532H1",
    title: "Digital Systems Design",
    area: ["ANALOG_DIGITAL", "HARDWARE_NETWORKS"],
    lectureHours: 38.4,
    tutorialHours: 0,
    practicalHours: 38.4,
    prerequisites: ["ECE342H1", "ECE352H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "An introduction to dynamic systems and their control. Differential equation models of mechanical, electrical, and electromechanical systems. State variable form. Linearization of nonlinear models and transfer functions. Use of Laplace transform to solve ordinary differential equations. Conversion of models from state variable form to transfer function representation and vice versa. Block diagrams and their manipulation. Time response: transient analysis and performance measures. Properties of feedback control systems. Steady state tracking: the notion of system type. The concept of stability of feedback systems, Routh-Hurwitz stability criterion. Frequency response and stability in the frequency domain. Root locus. Bode and Nyquist plots and their use in feedback control design.",
    code: "ECE311H1",
    title: "Introduction to Control Systems",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["MAT290H1", "MAT291H1", "ECE216H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "An introductory course in analog and digital communication systems. Analog and digital signals. Signal representation and Fourier transforms; energy and power spectral densities; bandwidth. Distortionless analog communication; amplitude, frequency and phase modulation systems; frequency division multiplexing. Sampling, quantization and pulse code modulation (PCM). Baseband digital communication; intersymbol interference (ISI); Nyquist's ISI criterion; eye diagrams. Passband digital communications; amplitude-, phase- and frequency-shift keying; signal constellations. Performance analysis of analog modulation schemes in the presence of noise. Performance analysis of PCM in noise.",
    code: "ECE316H1",
    title: "Communication Systems",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["MAT290H1", "ECE216H1", "MAT389H1", "ECE355H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 2,
    corequisiteAmount: 0,
  },
  {
    description:
      "Generation, transmission and the significance of bioelectricity in neural networks of the brain. Topics covered include: (i) Basic features of neural systems. (ii) Ionic transport mechanisms in cellular membranes. (iii) Propagation of electricity in neural cables. (iv) Extracellular electric fields. (v) Neural networks, neuroplasticity and biological clocks. (vi) Learning and memory in artificial neural networks. Laboratory experiences include: (a) Biological measurements of body surface potentials (EEG and EMG). (b) Experiments on computer models of generation and propagation of neuronal electrical activities. (c) Investigation of learning in artificial neural networks. This course was previously offered as ECE445H1.",
    code: "BME445H1",
    title: "Neural Bioelectricity",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 16.2,
    prerequisites: ["ECE159H1", "ECE110H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "An introductory course to medical imaging and is designed as a final year course for engineers. The main clinical imaging modalities are covered: magnetic resonance imaging, ultrasound imaging, x-ray and computed tomography, nuclear medicine, and clinical optical imaging. Emphasis is placed on the underlying physical and mathematical concepts behind each modality, and applications are discussed in the context of how different modalities complement one another in the clinical setting. Early year engineering concepts are extensively used, including: basic electromagnetics theory, fields and waves, signals and systems, digital signal processing, differential equations and calculus, and probability and random processes. The laboratories involve image reconstruction and analysis for the various imaging modalities and a live animal imaging session.",
    code: "BME595H1",
    title: "Medical Imaging",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 25.6,
    tutorialHours: 12.8,
    practicalHours: 38.4,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Events, sample space, axioms of probability. Discrete and continuous random variables, distribution and density functions. Bernoulli trials, Binomial, geometric, Poisson, exponential and Gaussian distributions. Expectation, moments, characteristic function and correlation coefficient. Functions of random variables. Random vectors, joint distributions, transformations. Applications will be chosen from communication theory, estimation and hypothesis testing, predictive analytics and other areas of electrical and computer engineering.",
    code: "ECE302H1",
    title: "Probability and Applications",
    area: ["CONTROL_COMM_SIGNAL", "HARDWARE_NETWORKS"],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 0,
    prerequisites: ["MAT290H1", "MAT291H1", "ECE216H1"],
    corequisites: [],
    exclusions: ["ECE286H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "State space analysis of linear systems, the matrix exponential, linearization of nonlinear systems. Structural properties of linear systems: stability, controllability, observability, stabilizability, and detectability. Pole assignment using state feedback, state estimation using observers, full-order and reduced-order observer design, design of feedback compensators using the separation principle, control design for tracking. Control design based on optimization, linear quadratic optimal control, the algebraic Riccati equation. Laboratory experiments include computer-aided design using MATLAB and the control of an inverted pendulum on a cart.",
    code: "ECE410H1",
    title: "Linear Control Systems",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE311H1"],
    corequisites: [],
    exclusions: ["ECE557H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Basic concepts of digital communication. Baseband data transmission, intersymbol interference, Nyquist pulse shaping, equalization, line coding, multi-path fading, diversity. Binary and M-ary modulation schemes, synchronization. Signal space concepts, optimum receivers, coherent and noncoherent detectors. Information theory, source encoding, error control coding, block and convolutional codes.",
    code: "ECE417H1",
    title: "Digital Communication",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE302H1", "ECE316H1", "ECE286H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 2,
    corequisiteAmount: 0,
  },
  {
    description:
      "An Introduction to the basic theory, the fundamental algorithms, and the computational toolboxes of machine learning. The focus is on a balanced treatment of the practical and theoretical approaches, along with hands on experience with relevant software packages. Supervised learning methods covered in the course will include: the study of linear models for classification and regression, neural networks and support vector machines. Unsupervised learning methods covered in the course will include: principal component analysis, k-means clustering, and Gaussian mixture models. Theoretical topics will include: bounds on the generalization error, bias-variance tradeoffs and the Vapnik-Chervonenkis (VC) dimension. Techniques to control overfitting, including regularization and validation, will be covered.",
    code: "ECE421H1",
    title: "Introduction to Machine Learning",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 0,
    prerequisites: [
      "ECE286H1",
      "STA286H1",
      "ECE302H1",
      "MIE231H1",
      "CHE223H1",
      "MIE236H1",
      "MSE238H1",
    ],
    corequisites: [],
    exclusions: ["CSC411H1", "ECE521H1"],
    recommendedPrep: [],
    prerequisiteAmount: 2,
    corequisiteAmount: 0,
  },
  {
    description:
      "An introductory course in digital filtering and applications. Introduction to real world signal processing. Review of sampling and quantization of signals. Introduction to the discrete Fourier transform and its properties. The fast Fourier transform. Fourier analysis of signals using the discrete Fourier transform. Structures for discrete-time systems. Design and realization of digital filters: finite and infinite impulse response filters. DSP applications in areas such as communications, multimedia, video coding, human computer interaction and medicine.",
    code: "ECE431H1",
    title: "Digital Signal Processing",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Provides an overview of the fundamental principles and clinical applications of neuromodulation. Topics include (i) overview of the human nervous system & neural oscillations, (ii) introduction to electrical-neural interfaces, (iii) fundamentals of neural recording, neural stimulation & signal processing as well as (iv) instrumentation and clinical applications of commonly used neuromodalities including Electroencephalography (EEG), Deep brain stimulation (DBS), Transcranial magnetic stimulation (TMS) and Functional electrical stimulation (FES).",
    code: "ECE441H1",
    title: "Interfacing & Modulating the Nervous System",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 38.4,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: ["BME445H1"],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Classification of robot manipulators, kinematic modeling, forward and inverse kinematics, velocity kinematics, path planning, point-to-point trajectory planning, dynamic modeling, Euler-Lagrange equations, inverse dynamics, joint control, computed torque control, passivity-based control, feedback linearization.",
    code: "ECE470H1",
    title: "Robot Modeling and Control",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE311H1", "ECE356H1"],
    corequisites: [],
    exclusions: ["AER525H1"],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "The economic evaluation and justification of engineering projects and investment proposals are discussed. Cost concepts; financial and cost accounting; depreciation; the time value of money and compound interest; inflation; capital budgeting; equity, bond and loan financing; income tax and after-tax cash flow in engineering project proposals; measures of economic merit in the public sector; sensitivity and risk analysis. Applications: evaluations of competing engineering project alternatives; replacement analysis; economic life of assets; lease versus buy decisions; break-even and sensitivity analysis. Entrepreneurship and the Canadian business environment will be discussed.",
    code: "ECE472H1",
    title: "Engineering Economic Analysis & Entrepreneurship",
    area: [],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 0,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Introduction to the principles and properties of random processes, with applications to communications, control systems, and computer science. Random vectors, random convergence, random processes, specifying random processes, Poisson and Gaussian processes, stationarity, mean square derivatives and integrals, ergodicity, power spectrum, linear systems with stochastic input, mean square estimation, Markov chains, recurrence, absorption, limiting and steady-state distributions, time reversibility, and balance equations.",
    code: "ECE537H1",
    title: "Random Processes",
    area: ["CONTROL_COMM_SIGNAL", "HARDWARE_NETWORKS"],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 0,
    prerequisites: ["ECE286H1", "ECE302H1"],
    corequisites: ["ECE355H1"],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Introduces physiological concepts and selected physiological control systems present in the human body, and proposes quantitative modeling approaches for these systems. Topics covered will include (1) the endocrine system and its subsystems, including glucose regulation and the stress response, (2) the cardiovascular system and related aspects such as cardiac output, venous return, control of blood flow by the tissues, and nervous regulation of circulation, and (3) the nervous and musculoskeletal systems, including the control of voluntary motion. Linear control theory will be used to develop skills in system modeling and examine concepts of system response and system control in the context of a healthy human body.",
    code: "BME331H1",
    title: "Physiological Control Systems",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 12.8,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "This course will focus on different classes of probabilistic models and how, based on those models, one deduces actionable information from data. The course will start by reviewing basic concepts of probability including random variables and first and second-order statistics. Building from this foundation the course will then cover probabilistic models including vectors (e.g., multivariate Gaussian), temporal (e.g., stationarity and hidden Markov models), and graphical (e.g., factor graphs). On the inference side topics such as hypothesis testing, marginalization, estimation, and message passing will be covered. Applications of these tools cover a vast range of data processing domains including machine learning, communications, search, recommendation systems, finance, robotics and navigation.",
    code: "ECE368H1",
    title: "Probabilistic Reasoning",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 0,
    prerequisites: ["ECE286H1", "ECE302H1"],
    corequisites: [],
    exclusions: ["CSC412H1"],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "An introduction to adaptive control and reinforcement learning for discrete-time deterministic linear systems. Topics include: discrete-time state space models; stability of discrete time systems; parameter adaptation laws; error models in adaptive control; persistent excitation; controllability and pole placement; observability and observers; classical regulation in discrete-time; adaptive regulation; dynamic programming; Rescorla-Wagner model; value iteration methods; Q-learning; temporal difference learning.",
    code: "ECE411H1",
    title: "Adaptive Control and Reinforcement Learning",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE311H1", "ECE356H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Topics in the engineering area of multimedia systems with particular emphasis on the theory, design features, performance, complexity analysis, optimization and application of multimedia engineering technologies. Topics include sound/audio, image and video characterization, compression, source entropy and hybrid coding, transform coding, wavelet-based coding, motion estimation, JPEG coding, digital video coding, MPEG-1/2 coding, content-based processing, and MPEG-7.",
    code: "ECE462H1",
    title: "Multimedia Systems",
    area: ["CONTROL_COMM_SIGNAL", "HARDWARE_NETWORKS"],
    lectureHours: 38.4,
    tutorialHours: 0,
    practicalHours: 25.6,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "The radio medium, radio communication system examples. Link budget: cable losses, propagation loss, antenna gains. Basic concepts of propagation: path loss, multi-path propagation and fading. Raleigh and Rician fading models, Doppler shift, delay spread, coherence time and coherence bandwidth of the channel. Analog modulation schemes and their bandwidths. Digital modulation schemes and their bandwidths and bit rates: BPSK, QPSK, MSK, GMSK. Basic concepts of speech coding. Error correction coding, interleaving, and multiple access frame structure. The physical layer description of the AMPS, IS-54, and GSM cellular systems. The cellular concept: frequency re-use, re-use cluster concept. Channel allocation. Cellular system architecture for AMPS, IS-54, and GSM. Hand-offs and transmitter power control. Cellular traffic, call blocking, concept of Erlangs. Basic ideas in spread spectrum modulation, spreading codes, bit error probability. Orthogonal and non-orthogonal CDMA Basic concepts in CDMA networks.",
    code: "ECE464H1",
    title: "Wireless Communication",
    area: ["CONTROL_COMM_SIGNAL", "HARDWARE_NETWORKS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE302H1", "ECE316H1", "ECE417H1", "ECE286H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 2,
    corequisiteAmount: 0,
  },
  {
    description:
      "Provides fundamental knowledge in the expanding field of Intelligent Image Processing, Humanistic Intelligence, Wearable AI, Spatial XR (VR/AR/MR), Wearable Computing, Human Computer Interaction (HCI), Mobile Multimedia, Augmented Reality, Mediated Reality, CyborgLogging, vision-based mobility devices and assistive technologies like the Freehicle (vehicle of freedom for mobility for persons with disabilities). Key topics include Mersivity (Socio-Cyber-Physical border or boundary between us and our surroundings), vision-based human-computer interaction. Personal Safety Devices, lifelong personal video capture, EyeTap principle, comparametric equations, photoquantigraphic imaging, lightvector spaces, anti-homomorphic imaging, application, algebraic projective geometry of 360-degree imaging, underwater imaging.",
    code: "ECE516H1",
    title: "Intelligent Image Processing",
    area: ["CONTROL_COMM_SIGNAL"],
    lectureHours: 38.4,
    tutorialHours: 0,
    practicalHours: 38.4,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Layered network architectures; overview of TCP/IP protocol suite. Introduction to sockets; introduction to application layer protocols. Peer-to-Peer Protocols: ARQ; TCP reliable stream service; flow control. Data Link Controls: Framing; PPP; HDLC. Medium access control and LANs: Aloha; Ethernet; Wireless LANs; Bridges. Packet Switching: Datagram and virtual circuit switching; Shortest path algorithms; Distance vector and link state algorithms.",
    code: "ECE361H1",
    title: "Computer Networks I",
    area: ["HARDWARE_NETWORKS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE286H1"],
    corequisites: ["ECE302H1"],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "This course will cover the fundamentals of protocols for packet switching networks with emphasis on Internet type of networks including the following topics: the Internetworking concept and architectural model; data link layer (Ethernet and PPP); service interface; Internet addresses; address resolution protocol; Internet protocol (connectionless datagram delivery); routing IP datagrams; Internet control message protocol (error and control messages); subnet and supernet address extensions; ping program; traceroute program; user datagram protocol; reliable stream transport service (TCP); the socket interface; routing (GGP, EGP, IP, OSPF, HELLO); Internet multicasting; domain name system; applications such as HTTP, electronic mail, and SNMP; Internet security and firewall design; Ipv6, RSVP, flows, and ISIP.",
    code: "ECE461H1",
    title: "Internetworking",
    area: ["HARDWARE_NETWORKS", "SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 6.4,
    practicalHours: 19.2,
    prerequisites: ["ECE361H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Performance analysis and metrics and cost. Instruction set architectures. Instruction-level parallelism: pipelining, superscalar, dynamic scheduling, VLIW processors. Data-level prallelism: vector processors, GPUs. Thread-level parallelism: multiprocessors, multi-core, coherence, simultaneous multi-threading. Memory hierarchies: caches and virtual memory support. Simulation tools and methods. Limited Enrollment.",
    code: "ECE552H1",
    title: "Computer Architecture",
    area: ["HARDWARE_NETWORKS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE243H1", "ECE352H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "As computers permeate our society, the security of such computing systems is becoming of paramount importance. This course covers principles of computer systems security. To build secure systems, one must understand how attackers operate. This course starts by teaching students how to identify security vulnerabilities and how they can be exploited. Then techniques to create secure systems and defend against such attacks will be discussed. Industry standards for conducting security audits to establish levels of security will be introduced. The course will include an introduction to basic cryptographic techniques as well as hardware used to accelerate cryptographic operations in ATM's and webservers.",
    code: "ECE568H1",
    title: "Computer Security",
    area: ["HARDWARE_NETWORKS", "SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 0,
    practicalHours: 38.4,
    prerequisites: ["ECE344H1", "ECE353H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Design of digital hardware components and embedded systems. Finite state machines and the algorithmic state machine representation. Timing analysis of single and multi-clock designs. Numeric representation and arithmetic circuits: binary addition, subtraction, multiplication and division; IEEE 754 floating point representation. Introduction to hardware architecture of embedded systems; on-chip buses, particularly the AMBA/AXI standard. Processor design and pipelining. Memory types, interfacing and direct memory access. Off-chip peripherals and communication protocols.",
    code: "ECE342H1",
    title: "Computer Hardware",
    area: ["HARDWARE_NETWORKS"],
    lectureHours: 38.4,
    tutorialHours: 0,
    practicalHours: 38.4,
    prerequisites: ["ECE241H1", "ECE243H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Traffic modeling; network calculus; traffic classification; traffic regulation: shaping, filtering, policing, leaky bucket; queueing systems; scheduling; quality of service: Diffserv and IntServ/RSVP; multi-protocol label switching; call admission control / congestion control; switching; pricing; optical networks.",
    code: "ECE466H1",
    title: "Computer Networks II",
    area: ["HARDWARE_NETWORKS"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE361H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Operating system structures, concurrency, synchronization, deadlock, CPU scheduling, memory management, file systems. The laboratory exercises will require implementation of part of an operating system.",
    code: "ECE344H1",
    title: "Operating Systems",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 0,
    practicalHours: 38.4,
    prerequisites: ["ECE244H1", "ECE243H1"],
    corequisites: [],
    exclusions: ["ECE353H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Design and analysis of algorithms and data structures that are essential to engineers in every aspect of the computer hardware and software industry. Recurrences, asymptotics, summations, trees and graphs. Sorting, search trees and balanced search trees, amortized analysis, hash functions, dynamic programming, greedy algorithms, basic graph algorithms, minimum spanning trees, shortest paths, introduction to NP completeness and new trends in algorithms and data structures.",
    code: "ECE345H1",
    title: "Algorithms and Data Structures",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 0,
    prerequisites: ["ECE244H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "A basic introduction to the history, technology, programming and applications of the fast evolving field of deep learning. Topics to be covered may include neural networks, autoencoders/decoders, recurrent neural networks, natural language processing, and generative adversarial networks. Special attention will be paid to fairness and ethics issues surrounding machine learning. An applied approach will be taken, where students get hands-on exposure to the covered techniques through the use of state-of-the-art machine learning software frameworks.",
    code: "APS360H1",
    title: "Applied Fundamentals of Deep Learning",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 0,
    practicalHours: 12.8,
    prerequisites: [
      "APS105H1",
      "APS106H1",
      "ESC180H1",
      "CSC180H1",
      "APS163",
      "MAT187H1",
      "ESC195H1",
      "MAT185H1",
      "MAT188H1",
    ],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [
      "CHE223H1",
      "CME263H1",
      "ECE302H1",
      "MIE231H1",
      "MIE236H1",
      "MSE238H1",
      "STA286H1",
      "ECE286H1",
      "MIE286H1",
    ],
    prerequisiteAmount: 3,
    corequisiteAmount: 0,
  },
  {
    description:
      "Identification and characterization of the objects manipulated in computer graphics, the operations possible on these objects, efficient algorithms to perform these operations, and interfaces to transform one type of object to another. Display devices, display data structures and procedures, graphical input, object modelling, transformations, illumination models, primary and secondary light effects; graphics packages and systems. Students, individually or in teams, implement graphical algorithms or entire graphics systems. Recommended Preparation: MAT244H1 NOTE: Students not enrolled in the Computer Science Major or Specialist program at A&S, UTM, or UTSC, or the Data Science Specialist at A&S, are limited to a maximum of 1.5 credits in 300-/400-level CSC/ECE courses.",
    code: "CSC317H1",
    title: "Computer Graphics",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 16.4,
    practicalHours: 0,
    prerequisites: [
      "APS105H1",
      "CSC180H1",
      "ESC180H1",
      "MAT185H1",
      "MAT188H1",
      "MAT291H1",
      "MAT292H1",
      "MAT294H1",
    ],
    corequisites: [],
    exclusions: ["CSC418H1", "CSCD18H3"],
    recommendedPrep: ["MAT244H1"],
    prerequisiteAmount: 3,
    corequisiteAmount: 0,
  },
  {
    description:
      "Introduction to database management systems. The relational data model. Relational algebra. Querying and updating databases: the query language SQL. Application programming with SQL. Integrity constraints, normal forms, and database design. Elements of database system technology: query processing, transaction management.",
    code: "CSC343H1",
    title: "Introduction to Databases",
    area: ["SOFTWARE"],
    lectureHours: 36,
    tutorialHours: 0,
    practicalHours: 0,
    prerequisites: [
      "CSC111H1",
      "CSC165H1",
      "CSC240H1",
      "MAT135H1",
      "MAT136H1",
      "MAT135Y1",
      "MAT137Y1",
      "MAT157Y1",
      "MAT186H1",
      "MAT187H1",
      "MAT194H1",
      "MAT195H1",
      "ESC194H1",
      "ESC195H1",
      "CSC207H1",
      "CSC207H5",
      "CSCB07H3",
      "ECE345H1",
      "ESC190H1",
    ],
    corequisites: [],
    exclusions: ["CSC343H5", "CSCC43H3", "MIE253H1"],
    recommendedPrep: [],
    prerequisiteAmount: 3,
    corequisiteAmount: 0,
  },
  {
    description:
      "Theories and algorithms that capture (or approximate) some of the core elements of computational intelligence. Topics include: search; logical representations and reasoning, classical automated planning, representing and reasoning with uncertainty, learning, decision making (planning) under uncertainty. Assignments provide practical experience, in both theory and programming, of the core topics.",
    code: "CSC384H1",
    title: "Introduction to Artificial Intelligence",
    area: ["SOFTWARE"],
    lectureHours: 24,
    tutorialHours: 12,
    practicalHours: 0,
    prerequisites: [
      "CSC263H1",
      "CSC265H1",
      "CSC263H5",
      "CSCB63H3",
      "ECE345H1",
      "ECE358H1",
      "MIE245H1",
      "CSC148H1",
      "STA220H1",
      "STA237H1",
      "STA247H1",
      "STA255H1",
      "STA257H1",
      "STAB57H3",
      "STAB52H3",
      "ECE302H1",
      "STA286H1",
      "CHE223H1",
      "CME263H1",
      "MIE231H1",
      "MIE236H1",
      "MSE238H1",
      "ECE286H1",
      "PSY201H1",
    ],
    corequisites: [],
    exclusions: ["CSC384H5", "CSCD84H3", "MIE369H1"],
    recommendedPrep: [],
    prerequisiteAmount: 2,
    corequisiteAmount: 0,
  },
  {
    description:
      "Study of programming styles and paradigms. Included are object-oriented scripting, functional and logic-based approaches. Languages that support these programming styles will be introduced. Languages treated include Python, Lisp or Scheme and Prolog.",
    code: "ECE326H1",
    title: "Programming Languages",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: [],
    corequisites: [],
    exclusions: ["CSC324H1", "CSC326H1"],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "The collaborative software development process. Software requirements elicitation and specifications. Software design techniques. Techniques for developing large software systems. Software testing, quality assurance, documentation, and maintenance. Open-source software and web application design.",
    code: "ECE444H1",
    title: "Software Engineering",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 38.4,
    prerequisites: ["ECE344H1", "ECE353H1", "ECE297H1"],
    corequisites: [],
    exclusions: ["CSC444H1"],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Fundamental techniques for programming computer systems, with an emphasis on obtaining good performance. Topics covered include: how to measure and understand program and execution behaviour, how to get the most out of an optimizing compiler, how memory is allocated and managed, and how to exploit caches and the memory hierarchy. Furthermore, current trends in multicore, multithreaded and data parallel hardware, and how to exploit parallelism in their programs will be covered.",
    code: "ECE454H1",
    title: "Computer Systems Programming",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 0,
    practicalHours: 38.4,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Compiler organization, compiler writing tools, use of regular expressions, finite automata and context-free grammars, scanning and parsing, runtime organization, semantic analysis, implementing the runtime model, storage allocation, code generation.",
    code: "ECE467H1",
    title: "Compilers & Interpreters",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE243H1", "ECE352H1"],
    corequisites: [],
    exclusions: ["CSC467H1"],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Design issues in distributed systems: heterogeneity, security, transparency, concurrency, fault-tolerance; networking principles; request-reply protocol; remote procedure calls; distributed objects; middleware architectures; CORBA; security and authentication protocols; distributed file systems; name services; global states in distributed systems; coordination and agreement; transactions and concurrency control; distributed transactions; replication.",
    code: "ECE419H1",
    title: "Distributed Systems",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 12.8,
    practicalHours: 19.2,
    prerequisites: ["ECE344H1", "ECE353H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
  {
    description:
      "Modern technologies in the biosciences generate tremendous amounts of biological data ranging from genomic sequences to protein structures to gene expression. Biocomputations are the computer algorithms used to reveal the hidden patterns within this data. Course topics include basic concepts in molecular cell biology, pairwise sequence alignment, multiple sequence alignment, fast alignment algorithms, deep learning approaches, phylogenetic prediction, structure-based computational methods, gene finding and annotation.",
    code: "ECE448H1",
    title: "Biocomputation",
    area: ["SOFTWARE"],
    lectureHours: 38.4,
    tutorialHours: 25.6,
    practicalHours: 0,
    prerequisites: [],
    corequisites: [],
    exclusions: [],
    recommendedPrep: [],
    prerequisiteAmount: 0,
    corequisiteAmount: 0,
  },
  {
    description:
      "Provides a comprehensive understanding of quantum information processing, focusing on software tools and algorithms for quantum computing. The material covers foundational quantum mechanics background, introduces quantum computing basics, and explores key software frameworks and algorithms. Through programming exercises and projects, students develop skills in designing and implementing quantum algorithms. Exercises are conducted using prominent quantum simulators.",
    code: "ECE484H1",
    title: "Quantum Information Processing: Algorithms & Software",
    area: ["SOFTWARE"],
    lectureHours: 36.6,
    tutorialHours: 24.4,
    practicalHours: 0,
    prerequisites: ["MIE286H1", "ECE302H1"],
    corequisites: [],
    exclusions: [],
    recommendedPrep: ["PHY365H1"],
    prerequisiteAmount: 1,
    corequisiteAmount: 0,
  },
];