PADDING_VALUE = 0
MAX_SKILLS_INTERESTS_LENGTH = 288
MAX_MINORS_CERTIFICATES_LENGTH = 26
MAX_ECE_AREAS_LENGTH = 6
MAX_DESIRED_DESIGNATION_LENGTH = 2

STRING_EMBEDDING_DIMENSION = 384
ID_EMBEDDING_SIZE = 64
ECE_AREAS_EMBEDDING_SIZE = 32
DESIRED_DESIGNATION_EMBEDDING_SIZE = 16
BINARY_INPUT_EMBEDDING_SIZE = 3
BINARY_EMBEDDING_SIZE = 4

DATASET_SIZE = 434
NUMBER_OF_EPOCHS = 5
BATCH_SIZE = 32
SHUFFLE_SAMPLES_SIZE = 1024

FIRST_DENSE_LAYER = 128
SECOND_DENSE_LAYER = 64

TFRECORD_FILE_PATH = "./recommendation-model/samples.tfrecord"
TFRECORD_BUFFER_SIZE = 512 * 512 # 256kB
MODEL_FILE_PATH = "./recommendation-model/model.keras"

MAX_RECOMMENDED_COURSES = 15