export const TAGLINE =
  "Guaranteeing you navigate course selection with passion & confidence";
export const GENERIC_ERROR = "Something went wrong. Please try again";
export const ERROR_MESSAGE_MARGIN_TOP = "79px";
export const DUPLICATE_EMAIL_ERROR = "Email is already in use";
export const INVALID_LOGIN_ERROR = "Invalid login details. Please try again";
export const EMAIL_ERROR = "Please enter a valid email address";
export const LOGGED_IN = "Logged In";
export const ALL_EMAIL_TOPICS = "All Email Topics";
export const EMAIL_TOPICS = [
  ALL_EMAIL_TOPICS,
  "Course Selection Advice",
  "Course Availability",
  "Course Information",
  "Course Registration Inquiry",
  "Course Requirements",
  "Degree Requirements",
  "Designation Inquiry",
  "Minors/Certificates Inquiry",
  "Electives Inquiry",
  "Humanities Inquiry",
  "Timetable Conflicts",
  "Timetable Inquiry",
  "Waitlist Inquiry",
  "Course Drop Inquiry",
  "Other",
];

export const ECE_AREAS = {
  PHOTONICS_SEMICONDUCTOR: "Photonics & Semiconductor Physics",
  ENERGY_ELECTROMAGNETICS: "Electromagnetics & Energy Systems",
  ANALOG_DIGITAL: "Analog & Digital Electronics",
  CONTROL_COMM_SIGNAL: "Control, Communications & Signal Processing",
  HARDWARE_NETWORKS: "Computer Hardware & Computer Networks",
  SOFTWARE: "Software",
};
export const DESIGNATIONS = {
  COMPUTER: "Computer Engineering",
  ELECTRICAL: "Electrical Engineering",
};
export const NO_DESIGNATION = "No Designation";
export const MINOR = "MINOR";
export const CERTIFICATE = "CERTIFICATE";

export const MINORS = [
  "Advanced Manufacturing",
  "Artificial Intelligence Engineering",
  "Bioengineering",
  "Biomedical Engineering",
  "Engineering Business",
  "Environmental Engineering",
  "Global Leadership",
  "Music Performance",
  "Nanoengineering",
  "Robotics & Mechatronics",
  "Sustainable Energy",
];

export const CERTIFICATES = [
  "Artificial Intelligence Engineering",
  "Communication",
  "Electric Vehicle Design",
  "Engineering Business",
  "Engineering Leadership",
  "Entrepreneurship, Innovation and Small Business",
  "Forensic Engineering",
  "Global Engineering",
  "Justice, Equity, Diversity and Inclusion in Engineering",
  "Mineral Resources",
  "Music Technology",
  "Nuclear Engineering",
  "Public Health & Engineering",
  "Public Policy and Engineering",
  "Renewable Resources Engineering",
];

// Source: https://www.bitglint.com/academic-interests-list/
// Generic interests are at the top of the list
export const NUMBER_OF_GENERIC_INTERESTS = 14;
export const INTERESTS = [
  "Science & Technology",
  "Mathematics & Engineering",
  "Health & Medicine",
  "Social Sciences & Humanities",
  "Business & Finance",
  "Arts & Media",
  "Education & Communication",
  "Environmental & Earth Sciences",
  "Law & Criminal Justice",
  "IT & Digital Fields",
  "Liberal Arts & Cultural Studies",
  "Sports & Physical Sciences",
  "Space & Future Studies",
  "Personal Development & Lifestyle Fields",

  "Artificial Intelligence",
  "Data Science",
  "Cybersecurity",
  "Robotics",
  "Biomedical Engineering",
  "Astronomy",
  "Quantum Physics",
  "Genetics",
  "Environmental Science",
  "Astrobiology",

  "Applied Mathematics",
  "Aerospace Engineering",
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Chemical Engineering",
  "Nuclear Engineering",
  "Cryptography",
  "Statistics",
  "Game Development",

  "Medicine",
  "Nursing",
  "Psychology",
  "Pharmacy",
  "Physical Therapy",
  "Public Health",
  "Genetic Counseling",
  "Sports Medicine",
  "Neuroscience",
  "Dentistry",

  "History",
  "Political Science",
  "Sociology",
  "Anthropology",
  "Philosophy",
  "Linguistics",
  "Economics",
  "Psycholinguistics",
  "Archaeology",
  "Human Geography",

  "Entrepreneurship",
  "Marketing",
  "Finance",
  "Accounting",
  "E-commerce",
  "Real Estate",
  "Supply Chain Management",
  "Investment Banking",
  "Cryptocurrency & Blockchain",
  "Human Resources",

  "Graphic Design",
  "Photography",
  "Film & Media Studies",
  "Music Composition",
  "Acting & Theater",
  "Creative Writing",
  "Fashion Design",
  "Interior Design",
  "Animation",
  "Journalism",

  "Teaching",
  "Speech Therapy",
  "Library Science",
  "Translation & Interpretation",
  "Educational Psychology",
  "Sign Language Studies",
  "Curriculum Development",
  "Higher Education Administration",
  "Public Speaking",
  "Digital Communication",

  "Ecology",
  "Meteorology",
  "Marine Biology",
  "Geology",
  "Sustainability Studies",
  "Urban Planning",
  "Agricultural Science",
  "Wildlife Conservation",
  "Hydrology",
  "Forestry",

  "Law",
  "Criminal Justice",
  "Forensic Science",
  "International Law",
  "Human Rights Studies",
  "Cyber Law",
  "Corporate Law",
  "Environmental Law",
  "Intellectual Property Law",
  "Public Policy",

  "Software Development",
  "Web Development",
  "Cloud Computing",
  "User Experience (UX) Design",
  "Artificial Intelligence Ethics",
  "Virtual Reality (VR) & Augmented Reality (AR)",
  "Big Data Analytics",
  "Bioinformatics",
  "Internet of Things (IoT)",
  "Digital Marketing",

  "Classical Studies",
  "Comparative Literature",
  "Ethnic Studies",
  "Gender Studies",
  "Religious Studies",
  "Folklore & Mythology",
  "Translation Studies",
  "Cultural Anthropology",
  "Art History",
  "Media Studies",

  "Kinesiology",
  "Sports Science",
  "Recreational Therapy",
  "Coaching & Sports Management",
  "Adventure Education",
  "Athletic Training",
  "Dance Studies",
  "Martial Arts Studies",
  "Equine Studies",
  "Health & Wellness Studies",

  "Space Science",
  "Aerospace Medicine",
  "Astrophysics",
  "Exoplanet Studies",
  "Science Fiction Studies",
  "Space Law",
  "Futurism & Innovation",
  "Science Communication",
  "Renewable Energy Studies",
  "Nanotechnology",

  "Ethics & Moral Philosophy",
  "Mindfulness & Meditation Studies",
  "Personal Finance",
  "Nutrition Science",
  "Parenting & Child Development",
  "Hospitality & Tourism",
  "Culinary Arts",
  "Luxury Brand Management",
  "Tattoo Art & Culture",
  "Social Media Management",

  "Espionage & Intelligence Studies",
  "Magic & Illusion Studies",
  "Horology",
  "Theme Park Design",
  "Mycology",
  "Astrology",
  "Comic Book & Graphic Novel Studies",
  "Fan Culture & Fandom Studies",
  "LARP & Cosplay Studies",
  "Gastronomy",

  "Drone Technology",
  "Virtual Influencer Studies",
  "Esports Management",
  "Metaverse Studies",
  "Biomimicry",
  "Ocean Engineering",
  "Self-Driving Car Engineering",
  "Biodiversity Conservation",
  "Neurotechnology",
  "Digital Ethics",
  "Wearable Technology",
  "Bionics & Prosthetics",
  "3D Printing & Additive Manufacturing",
  "Synthetic Biology",
  "Cognitive Science",
  "Digital Twin Technology",
  "Agricultural Robotics",
  "Personalized Medicine",
  "Neuroprosthetics",
  "Aging & Longevity Studies",
  "Astrochemistry",
  "Quantum Computing",
  "Biohacking & Human Enhancement",
  "Alternative Energy",
  "Space Colonization",
  "Smart Cities",
  "Biodegradable Materials",
  "Voice Technology",
  "Self-Sustaining Ecosystems",
  "Carbon Capture Technology",

  "Experiential Marketing",
  "Food Science & Molecular Gastronomy",
  "Crisis Communication",
  "Transhumanism",
  "Future Warfare Studies",
  "Luxury Experience Design",
  "Experimental Music & Sound Studies",
  "Themed Entertainment Design",
  "Sensory Science",
  "Cultural Diplomacy",

  "Cryptozoology",
  "Astroarchaeology",
  "Steampunk & Retro-Futurism",
  "Survivalism & Prepping",
  "Parkour & Movement Studies",
  "eSports Psychology",
  "Tattoo Anthropology",
  "Mythical History & Folklore Analysis",
  "Sci-Fi & Fantasy World-Building",
  "Utopian & Dystopian Studies",
];

// Source: https://simplicable.com/edu/academic-skills
// Generic skills are at the top of the list
export const NUMBER_OF_GENERIC_SKILLS = 6;
export const SKILLS = [
  "Studying & Learning",
  "Reading & Writing",
  "Communication",
  "Technology",
  "Critical Thinking",
  "Research",

  "Academic Discourse",
  "Academic Writing",
  "Analysis",
  "Argument Development",
  "Attention to Detail",
  "Challenging Assumptions",
  "Coding & Scripting",
  "Collaborating",
  "Comparative Analysis",
  "Composition",
  "Concentration",
  "Constructive Criticism",
  "Creative Writing",
  "Critical Thinking",
  "Data Analysis",
  "Data Literacy",
  "Debate",
  "Design Thinking",
  "Developing a Hypothesis",
  "Digital Literacy",
  "Diligence",
  "Editing",
  "Ethical Reasoning",
  "Experiment Design",
  "Goal Planning",
  "Grammar & Punctuation",
  "Group Communication",
  "Handling Criticism",
  "Information Gathering",
  "Information Literacy",
  "Information Synthesis",
  "Interdisciplinary Collaboration",
  "Language Proficiency",
  "Listening",
  "Math Skills",
  "Media Literacy",
  "Non-verbal Communication",
  "Note-taking",
  "Numeracy",
  "Objectivity",
  "Organizing",
  "Peer Review",
  "People Skills",
  "Personal Resilience",
  "Persuasive Writing",
  "Planning",
  "Presentations",
  "Problem Solving",
  "Public Speaking",
  "Qualitative Analysis",
  "Quantitative Analysis",
  "Questioning",
  "Reading",
  "Research",
  "Self-Directed Learning",
  "Source Evaluation",
  "Statistical Analysis",
  "Study Skills",
  "Systematic Review",
  "Systems Thinking",
  "Teaching",
  "Test-taking",
  "Time Management",
  "Tolerance for Disagreement",
  "Tutoring",
  "Verbal Communication",
  "Visual Communication",
  "Vocabulary",
  "Work Ethic",
  "Writing",
];

export const TO = "To";
export const CC = "CC";

export const CART_PATH = "/cart";
export const FAVORITES_PATH = "/favorites";
export const TITLE_PATH = "/title";
export const DESCRIPTION_PATH = "/description";
export const ID_QUERY_PARAM = "?id=";

export const YES = "Yes";
export const NO = "No";

export const CONFLICT_FREE = "Conflict Free";
export const CONFLICTING = "Conflicting";
export const TIMETABLE_TITLE_PLACEHOLDER = "Enter timetable title";
export const TIMETABLE_DESCRIPTION_PLACEHOLDER = "Enter timetable description";
export const TITLE_ERROR_MESSAGE = "Please provide a title";